import { generateSEOMetadata } from '@/lib/seo/metadata';
import AnswerBlock from '@/components/seo/AnswerBlock';
import EntitySummary from '@/components/seo/EntitySummary';
import ProcessSteps from '@/components/seo/ProcessSteps';
import FAQBlock from '@/components/seo/FAQBlock';
import LocalIntentBlock from '@/components/seo/LocalIntentBlock';
import Link from 'next/link';
export const metadata = generateSEOMetadata({ title: 'Join as a Partner | Builders, Engineers & Suppliers | Buildogram', description: 'Buildogram Join as a Buildogram Partner - engineer-led, AI-driven construction support in Chennai.', path: '/join-as-partner' });
const STEPS = [{ title: '1. Initial Consultation', desc: 'Share your project details and requirements with our team for an accurate scope assessment.' }, { title: '2. Engineer Assignment', desc: 'A qualified engineer with relevant expertise is assigned to your project.' }, { title: '3. Assessment & Analysis', desc: 'Detailed assessment is performed following structured protocols and industry standards.' }, { title: '4. Report & Recommendations', desc: 'A formal report is issued with findings, recommendations, and next steps.' }, { title: '5. Follow-up Support', desc: 'Our team remains available for follow-up queries and engineer-led clarification.' }];
const FAQS = [{ question: 'How do I get started?', answer: 'Contact Buildogram through the form below or call our team. We will understand your requirements and connect you with the right engineer.' }, { question: 'What areas do you cover?', answer: 'We cover Chennai and all major districts in Tamil Nadu through our verified engineer and partner network.' }, { question: 'How long does this service take?', answer: 'Timelines depend on project scope. Initial consultation is typically within 24 hours. Full deliverables vary by service complexity.' }, { question: 'What makes Buildogram different?', answer: 'Buildogram is engineer-led and report-based — every recommendation is backed by field data, technical analysis, and documented evidence rather than verbal advice.' }];
export default function Page() { return (<main className='page' style={{ paddingTop: '80px', paddingBottom: '80px' }}><div className='sectionInner'><div style={{ marginBottom: '16px', fontSize: '14px', color: '#64748B' }}><a href='/' style={{ color: '#FC6E20' }}>Home</a> / <span style={{ color: '#0F172A', fontWeight: 600 }}>Join as a Buildogram Partner</span></div><h1 style={{ fontSize: '36px', fontWeight: 800, color: '#0F172A', marginBottom: '24px' }}>Join as a Buildogram Partner</h1><AnswerBlock question='Who can join the Buildogram partner network?' answer='Buildogram welcomes verified builders, RCC contractors, architects, structural engineers, surveyors, soil testing labs, NDT labs, piling contractors, material suppliers, steel fabricators, waterproofing vendors, interior designers, solar vendors, and maintenance vendors in Chennai and Tamil Nadu.' /><ProcessSteps title='How It Works' steps={STEPS} /><EntitySummary serviceName='Join as a Buildogram Partner' /><LocalIntentBlock /><FAQBlock title='Frequently Asked Questions' faqs={FAQS} /><div style={{ marginTop: '40px', padding: '24px', background: '#FFF7ED', borderRadius: '12px', border: '1px solid #FED7AA' }}><p style={{ fontWeight: 700, color: '#FC6E20', marginBottom: '12px' }}>Related Services</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>{[['Home Construction','/home-construction-chennai'],['BOQ Review','/boq-review-chennai'],['Structural Audit','/structural-audit-chennai'],['AI Tools','/ai-tools']].map(([label, href]) => (<Link key={href} href={href} style={{ padding: '8px 16px', background: 'white', border: '1px solid #FED7AA', borderRadius: '100px', color: '#374151', fontSize: '14px', fontWeight: 600, textDecoration: 'none' }}>{label}</Link>))}</div></div><div style={{ marginTop: '32px', textAlign: 'center' }}><Link href='/contact?type=partner' className='btn btn-primary btn-lg'>Get Started</Link></div></div></main>); }
