import { generateSEOMetadata } from '@/lib/seo/metadata';
import AnswerBlock from '@/components/seo/AnswerBlock';
import EntitySummary from '@/components/seo/EntitySummary';
import FAQBlock from '@/components/seo/FAQBlock';
import LocalIntentBlock from '@/components/seo/LocalIntentBlock';
import Link from 'next/link';
export const metadata = generateSEOMetadata({ title: 'AI Material Requirement Estimator | AI-Engineered Material Planning | Buildogram', description: 'AI Material Requirement Estimator by Buildogram. AI-engineered workflow for construction planning in Chennai.', path: '/ai-material-estimator' });
const FAQS = [{ question: 'Is this tool free to use?', answer: 'Yes. Buildogram AI tools are free to use. For detailed engineer-led review of your project, contact our team.' }, { question: 'How accurate are the AI-generated outputs?', answer: 'AI outputs are based on established construction frameworks and current Chennai market data. They are advisory in nature and should be reviewed by a qualified engineer before final decisions are made.' }, { question: 'Can I get a follow-up engineer review?', answer: 'Yes. After using any AI tool, you can request an engineer-led consultation through our contact page.' }, { question: 'Is my data stored?', answer: 'Inputs submitted through Buildogram AI tools are used only to generate your output and are handled as per our privacy policy.' }];
export default function Page() { return (<main className='page' style={{ paddingTop: '80px', paddingBottom: '80px' }}><div className='sectionInner'><div style={{ marginBottom: '16px', fontSize: '14px', color: '#64748B' }}><a href='/' style={{ color: '#FC6E20' }}>Home</a> / <a href='/ai-tools' style={{ color: '#FC6E20' }}>AI Tools</a> / <span style={{ color: '#0F172A', fontWeight: 600 }}>AI Material Requirement Estimator</span></div><h1 style={{ fontSize: '36px', fontWeight: 800, color: '#0F172A', marginBottom: '24px' }}>AI Material Requirement Estimator</h1><div style={{ background: '#FFF7ED', border: '1px solid #FED7AA', borderRadius: '12px', padding: '16px 20px', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '10px' }}><span style={{ background: '#DCFCE7', color: '#16A34A', fontSize: '11px', fontWeight: 700, padding: '4px 10px', borderRadius: '100px' }}>AI-Engineered</span><span style={{ fontSize: '14px', color: '#92400E' }}>AI-driven workflow — outputs are advisory and should be reviewed by a qualified engineer.</span></div><AnswerBlock question='What materials can the AI estimator calculate?' answer='The AI-engineered material estimator calculates approximate quantities for cement, TMT steel, M-sand, bricks or AAC blocks, ready mix concrete, and other key materials based on your project area, floor count, and structural type — helping you plan procurement and verify contractor material schedules.' /><div style={{ background: '#F8FAFC', borderRadius: '16px', padding: '32px', margin: '32px 0', textAlign: 'center' }}><h2 style={{ fontSize: '20px', fontWeight: 800, color: '#0F172A', marginBottom: '12px' }}>Use This Tool</h2><p style={{ color: '#64748B', marginBottom: '24px' }}>Submit your details below and our team will prepare your AI-engineered output and follow up with results.</p><Link href='/contact?type=ai' className='btn btn-primary btn-lg'>Get Started</Link></div><EntitySummary serviceName='AI Material Requirement Estimator' /><LocalIntentBlock /><FAQBlock title='Frequently Asked Questions' faqs={FAQS} /><div style={{ marginTop: '40px', padding: '24px', background: '#FFF7ED', borderRadius: '12px', border: '1px solid #FED7AA' }}><p style={{ fontWeight: 700, color: '#FC6E20', marginBottom: '12px' }}>Explore All AI Tools</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>{[['All AI Tools','/ai-tools'],['AI Cost Estimator','/ai-construction-cost-estimator'],['AI BOQ Checker','/ai-boq-checker'],['AI Quote Analyzer','/ai-contractor-quote-analyzer']].map(([label, href]) => (<Link key={href} href={href} style={{ padding: '8px 16px', background: 'white', border: '1px solid #FED7AA', borderRadius: '100px', color: '#374151', fontSize: '14px', fontWeight: 600, textDecoration: 'none' }}>{label}</Link>))}</div></div></div></main>); }
