'use client';
import { useState, useEffect } from 'react';
const STATUS_COLORS = { new:'#3B82F6',contacted:'#F59E0B',converted:'#10B981',closed:'#6B7280' };
export default function PilingAdmin() {
  const [leads,setLeads]=useState([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState('all');
  useEffect(()=>{fetch('/api/ops/piling-leads').then(r=>r.json()).then(d=>{setLeads(d.data||[]);setLoading(false);}).catch(()=>setLoading(false));},[]);
  const filtered=filter==='all'?leads:leads.filter(l=>l.status===filter);
  return (<div style={{padding:'32px',fontFamily:'Inter,sans-serif'}}><div style={{marginBottom:'24px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1 style={{fontSize:'22px',fontWeight:800,color:'#0F172A',margin:0}}>Piling & Foundation Leads</h1><p style={{color:'#64748B',fontSize:'14px',margin:'4px 0 0'}}>Bored piles, DMC piles, micro piles, and pile load test enquiries</p></div><select value={filter} onChange={e=>setFilter(e.target.value)} style={{padding:'8px 12px',border:'1px solid #E2E8F0',borderRadius:'8px',fontSize:'14px',color:'#374151'}}><option value="all">All Status</option><option value="new">New</option><option value="contacted">Contacted</option><option value="converted">Converted</option><option value="closed">Closed</option></select></div>{loading?(<div style={{textAlign:'center',color:'#64748B',padding:'60px'}}>Loading...</div>):filtered.length===0?(<div style={{textAlign:'center',color:'#64748B',padding:'60px',background:'#F8FAFC',borderRadius:'12px'}}>No piling leads yet.</div>):(<div style={{background:'white',border:'1px solid #E2E8F0',borderRadius:'12px',overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{background:'#F8FAFC',borderBottom:'1px solid #E2E8F0'}}>{['Name','Phone','Piling Type','Depth','No. of Piles','Locality','Status','Date'].map(h=>(<th key={h} style={{padding:'12px 16px',textAlign:'left',fontSize:'12px',fontWeight:700,color:'#64748B',textTransform:'uppercase',letterSpacing:'0.5px'}}>{h}</th>))}</tr></thead><tbody>{filtered.map((l,i)=>(<tr key={l.id} style={{borderBottom:'1px solid #F1F5F9',background:i%2===0?'white':'#FAFAFA'}}><td style={{padding:'12px 16px',fontWeight:600,color:'#0F172A',fontSize:'14px'}}>{l.name}</td><td style={{padding:'12px 16px',color:'#374151',fontSize:'14px'}}>{l.phone}</td><td style={{padding:'12px 16px',color:'#374151',fontSize:'14px'}}>{l.piling_type||'—'}</td><td style={{padding:'12px 16px',color:'#374151',fontSize:'14px'}}>{l.pile_depth||'—'}</td><td style={{padding:'12px 16px',color:'#374151',fontSize:'14px'}}>{l.no_of_piles||'—'}</td><td style={{padding:'12px 16px',color:'#374151',fontSize:'14px'}}>{l.locality||'—'}</td><td style={{padding:'12px 16px'}}><span style={{background:(STATUS_COLORS[l.status]||'#6B7280')+'20',color:STATUS_COLORS[l.status]||'#6B7280',fontSize:'11px',fontWeight:700,padding:'4px 10px',borderRadius:'100px',textTransform:'capitalize'}}>{l.status||'new'}</span></td><td style={{padding:'12px 16px',color:'#64748B',fontSize:'13px'}}>{l.created_at?new Date(l.created_at).toLocaleDateString('en-IN'):'—'}</td></tr>))}</tbody></table></div>)}</div>);
}
