import { generateSEOMetadata } from "@/lib/seo/metadata";
import AnswerBlock from "@/components/seo/AnswerBlock";
import EntitySummary from "@/components/seo/EntitySummary";
import ProcessSteps from "@/components/seo/ProcessSteps";
import FAQBlock from "@/components/seo/FAQBlock";
import LocalIntentBlock from "@/components/seo/LocalIntentBlock";
import Link from "next/link";
export const metadata = generateSEOMetadata({ title: "Topographic Survey in Chennai | Contour & Elevation Survey | Buildogram", description: "Topographic survey, contour mapping, and elevation data collection for construction planning in Chennai. Delivered as CAD drawings and GIS data by verified surveyors.", path: "/topographic-survey-chennai" });
const STEPS = [{ title: "1. Site Reconnaissance", desc: "Preliminary visit to assess site conditions, access routes, and control point availability." }, { title: "2. Total Station / DGPS Setup", desc: "Precision survey equipment is set up and calibrated using known benchmarks." }, { title: "3. Spot Level Collection", desc: "Elevation readings are collected across a grid pattern covering the full site area." }, { title: "4. Contour Processing", desc: "Spot level data is processed using CAD/GIS software to generate contour lines at required intervals." }, { title: "5. CAD Drawing & Report", desc: "Final topographic map is issued as a CAD DWG file with contours, spot levels, and area boundary." }];
const DELIVERABLES = ["Topographic Map (CAD DWG)", "Contour Map", "Spot Level Data", "Elevation Grid", "Site Area Boundary", "PDF Report"];
const FAQS = [{ question: "What is a topographic survey?", answer: "A topographic survey measures the elevation of the ground surface at various points across a site and uses this data to produce contour maps showing hills, slopes, and flat areas." }, { question: "Why is a topographic survey needed before construction?", answer: "It helps engineers design the correct foundation depth, drainage slopes, retaining walls, and site grading plan — preventing waterlogging and costly earthwork surprises." }, { question: "What is the difference between a topographic survey and a boundary survey?", answer: "A boundary survey establishes the legal plot limits. A topographic survey measures the elevation and terrain of the site. Both are often done together for construction planning." }, { question: "How long does a topographic survey take?", answer: "Depending on plot size, field work takes 1–3 days. CAD processing and report delivery typically takes 2–3 additional working days." }];
export default function Page() { return (<main className="page" style={{ paddingTop: "80px", paddingBottom: "80px" }}><div className="sectionInner"><div style={{ marginBottom: "16px", fontSize: "14px", color: "#64748B" }}><a href="/" style={{ color: "#FC6E20" }}>Home</a> / <span style={{ color: "#0F172A", fontWeight: 600 }}>Topographic Survey in Chennai</span></div><h1 style={{ fontSize: "36px", fontWeight: 800, color: "#0F172A", marginBottom: "24px" }}>Topographic Survey in Chennai</h1><AnswerBlock question="What does a topographic survey provide for a construction project?" answer="A topographic survey provides a scaled map of the site showing existing ground levels, elevation contours, slopes, and site boundaries — giving engineers the data needed to design foundations, drainage, and earthwork accurately." /><ProcessSteps title="Our Topographic Survey Process" steps={STEPS} /><div style={{ background: "#F8FAFC", borderRadius: "16px", padding: "32px", margin: "40px 0" }}><h2 style={{ fontSize: "22px", fontWeight: 800, color: "#0F172A", marginBottom: "16px" }}>What You Receive</h2><ul style={{ listStyle: "none", padding: 0, display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: "12px" }}>{DELIVERABLES.map(d => (<li key={d} style={{ display: "flex", alignItems: "center", gap: "8px", fontSize: "15px", color: "#374151" }}><span style={{ color: "#10B981", fontWeight: 700 }}>✓</span> {d}</li>))}</ul></div><EntitySummary serviceName="Topographic Survey in Chennai" /><LocalIntentBlock /><FAQBlock title="Frequently Asked Questions" faqs={FAQS} /><div style={{ marginTop: "40px", padding: "24px", background: "#FFF7ED", borderRadius: "12px", border: "1px solid #FED7AA" }}><p style={{ fontWeight: 700, color: "#FC6E20", marginBottom: "12px" }}>Related Services</p><div style={{ display: "flex", flexWrap: "wrap", gap: "10px" }}>{[["Land Survey", "/land-survey-chennai"], ["Drone Survey", "/drone-survey-chennai"], ["DGPS Survey", "/dgps-survey-chennai"], ["Construction Layout", "/construction-layout-marking-chennai"]].map(([label, href]) => (<Link key={href} href={href} style={{ padding: "8px 16px", background: "white", border: "1px solid #FED7AA", borderRadius: "100px", color: "#374151", fontSize: "14px", fontWeight: 600, textDecoration: "none" }}>{label}</Link>))}</div></div><div style={{ marginTop: "32px", textAlign: "center" }}><Link href="/contact?type=survey" className="btn btn-primary btn-lg">Request a Topographic Survey</Link></div></div></main>); }
