import BreadcrumbSchema from '@/components/seo/BreadcrumbSchema';
﻿import { generateSEOMetadata } from '@/lib/seo/metadata';
import AnswerBlock from '@/components/seo/AnswerBlock';
import EntitySummary from '@/components/seo/EntitySummary';
import FAQBlock from '@/components/seo/FAQBlock';
import LocalIntentBlock from '@/components/seo/LocalIntentBlock';
import Link from 'next/link';
export const metadata = generateSEOMetadata({ title: 'Piling & Foundation Materials Chennai | Casing, Bentonite | Buildogram', description: 'Source Piling & Foundation Materials in Chennai through Buildogram verified supplier network. Transparent rates, IS-standard specifications, and direct delivery in Chennai.', path: '/materials/piling-foundation-materials' });
const FAQS = [{ question: 'How do I get a material quote?', answer: 'Visit our Request Material Quote page or contact Buildogram with your material requirement, quantity, and delivery location. We will share competitive quotes from verified suppliers.' }, { question: 'Are the materials IS-certified?', answer: 'Yes. All materials in the Buildogram supplier network are expected to meet relevant IS (Indian Standard) specifications. Material Test Certificates (MTC) are available on request.' }, { question: 'Can I get materials delivered to my site?', answer: 'Yes. Our verified suppliers offer site delivery across Chennai. Delivery timelines and minimum order quantities vary by supplier and material type.' }, { question: 'Can I compare rates from multiple suppliers?', answer: 'Yes. Buildogram provides a comparative quote view for key materials so you can make informed decisions on brand and supplier selection.' }];
export default function Page() { return ( <><main className='page' style={{ paddingTop: '80px', paddingBottom: '80px' }}><div className='sectionInner'><div style={{ marginBottom: '16px', fontSize: '14px', color: '#64748B' }}><a href='/' style={{ color: '#FC6E20' }}>Home</a> / <a href='/materials' style={{ color: '#FC6E20' }}>Shop Materials</a> / <span style={{ color: '#0F172A', fontWeight: 600 }}>Piling & Foundation Materials in Chennai</span></div><h1 style={{ fontSize: '36px', fontWeight: 800, color: '#0F172A', marginBottom: '24px' }}>Piling & Foundation Materials in Chennai</h1><AnswerBlock question='What materials are used in bored pile construction?' answer='Bored pile construction uses steel casing (temporary or permanent), bentonite slurry for borehole stabilisation, reinforcement cages (TMT bars), and M25 to M35 grade concrete. Material specifications depend on soil conditions, pile diameter, and structural design requirements.' /><div style={{ background: '#F8FAFC', borderRadius: '16px', padding: '32px', margin: '40px 0' }}><h2 style={{ fontSize: '20px', fontWeight: 800, color: '#0F172A', marginBottom: '16px' }}>Why Source Through Buildogram?</h2><ul style={{ listStyle: 'none', padding: 0, display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '12px' }}>{['Verified supplier network','IS-standard specifications','Transparent rate comparison','Material Test Certificates on request','Site delivery across Chennai','No hidden charges'].map(d => (<li key={d} style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '15px', color: '#374151' }}><span style={{ color: '#10B981', fontWeight: 700 }}>✓</span> {d}</li>))}</ul></div><EntitySummary serviceName='Piling & Foundation Materials in Chennai' /><LocalIntentBlock /><FAQBlock title='Frequently Asked Questions' faqs={FAQS} /><div style={{ marginTop: '40px', padding: '24px', background: '#FFF7ED', borderRadius: '12px', border: '1px solid #FED7AA' }}><p style={{ fontWeight: 700, color: '#FC6E20', marginBottom: '12px' }}>Explore More Materials</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>{[['All Materials','/materials'],['Cement','/materials/cement'],['TMT Steel','/materials/tmt-steel'],['Ready Mix Concrete','/materials/ready-mix-concrete'],['Waterproofing','/materials/waterproofing']].map(([label, href]) => (<Link key={href} href={href} style={{ padding: '8px 16px', background: 'white', border: '1px solid #FED7AA', borderRadius: '100px', color: '#374151', fontSize: '14px', fontWeight: 600, textDecoration: 'none' }}>{label}</Link>))}</div></div><div style={{ marginTop: '32px', textAlign: 'center' }}><Link href='/material-quotes' className='btn btn-primary btn-lg'>Request Material Quote</Link></div></div></main>  <BreadcrumbSchema items={[{"name":"Home","path":"/"},{"name":"Materials","path":"/materials"},{"name":"Piling & Foundation Materials Chennai","path":"/materials/piling-foundation-materials"}]} />
    </>
  ); }
