import { generateSEOMetadata } from "@/lib/seo/metadata";
import AnswerBlock from "@/components/seo/AnswerBlock";
import EntitySummary from "@/components/seo/EntitySummary";
import ProcessSteps from "@/components/seo/ProcessSteps";
import FAQBlock from "@/components/seo/FAQBlock";
import LocalIntentBlock from "@/components/seo/LocalIntentBlock";
import Link from "next/link";
export const metadata = generateSEOMetadata({ title: "Bored Cast-In-Situ Piles Chennai | BCIS Piling Contractors | Buildogram", description: "Buildogram connects you with verified engineers for Bored Cast-In-Situ Piles in Chennai. Engineer-led, report-based service in Chennai.", path: "/bored-cast-in-situ-piles-chennai" });
const STEPS = [{ title: "1. Enquiry & Scope", desc: "Share your project details, site location, and service requirements with our team." }, { title: "2. Site Mobilisation", desc: "Verified engineers and equipment are mobilised to your site at the agreed schedule." }, { title: "3. Field Work & Testing", desc: "Field work is carried out following standard protocols. Data is recorded systematically." }, { title: "4. Lab Analysis", desc: "Samples and field data are processed in accredited laboratories where applicable." }, { title: "5. Report & Recommendation", desc: "A formal technical report is issued with findings, data, and engineer recommendations." }];
const DELIVERABLES = ["Technical Report", "Field Data Records", "Lab Test Results", "Engineer Recommendations", "Site Photographs"];
const FAQS = [{ question: "How do I request this service?", answer: "Contact Buildogram with your site address and project details. We will match you with a verified engineer and provide a project-specific quote." }, { question: "How long does the process take?", answer: "Timelines vary by service. Field work typically takes 1–3 days. Report preparation takes 3–7 working days after field completion." }, { question: "Do you provide services across Tamil Nadu?", answer: "Yes. Our verified engineer network covers Chennai and major districts across Tamil Nadu." }, { question: "Is the report accepted by structural engineers and banks?", answer: "Our reports are prepared by qualified engineers following IS standards and are suitable for submission to structural engineers, approving authorities, and financial institutions." }];
export default function Page() { return (<main className={"page"} style={{ paddingTop: "80px", paddingBottom: "80px" }}><div className={"sectionInner"}><div style={{ marginBottom: "16px", fontSize: "14px", color: "#64748B" }}><a href={"/"} style={{ color: "#FC6E20" }}>Home</a> / <span style={{ color: "#0F172A", fontWeight: 600 }}>Bored Cast-In-Situ Piles in Chennai</span></div><h1 style={{ fontSize: "36px", fontWeight: 800, color: "#0F172A", marginBottom: "24px" }}>Bored Cast-In-Situ Piles in Chennai</h1><AnswerBlock question={"What are bored cast-in-situ piles?"} answer={"Bored cast-in-situ (BCIS) piles are formed by drilling a borehole to the required depth, placing a reinforcement cage, and then pouring concrete in situ. They are widely used in urban Chennai where driven piles cause excessive noise and vibration near existing structures."} /><ProcessSteps title={"Our Process"} steps={STEPS} /><div style={{ background: "#F8FAFC", borderRadius: "16px", padding: "32px", margin: "40px 0" }}><h2 style={{ fontSize: "22px", fontWeight: 800, color: "#0F172A", marginBottom: "16px" }}>What You Receive</h2><ul style={{ listStyle: "none", padding: 0, display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: "12px" }}>{DELIVERABLES.map(d => (<li key={d} style={{ display: "flex", alignItems: "center", gap: "8px", fontSize: "15px", color: "#374151" }}><span style={{ color: "#10B981", fontWeight: 700 }}>✓</span> {d}</li>))}</ul></div><EntitySummary serviceName={"Bored Cast-In-Situ Piles in Chennai"} /><LocalIntentBlock /><FAQBlock title={"Frequently Asked Questions"} faqs={FAQS} /><div style={{ marginTop: "32px", textAlign: "center" }}><Link href={"/contact?type=piling"} className={"btn btn-primary btn-lg"}>Request This Service</Link></div></div></main>); }
