import { generateSEOMetadata } from "@/lib/seo/metadata";
import AnswerBlock from "@/components/seo/AnswerBlock";
import EntitySummary from "@/components/seo/EntitySummary";
import ProcessSteps from "@/components/seo/ProcessSteps";
import FAQBlock from "@/components/seo/FAQBlock";
import LocalIntentBlock from "@/components/seo/LocalIntentBlock";
import Link from "next/link";
export const metadata = generateSEOMetadata({ title: "Construction Layout Marking in Chennai | Column & Pile Point Marking | Buildogram", description: "Construction layout marking services in Chennai including column centre marking, pile point marking, and building footprint demarcation using total station survey.", path: "/construction-layout-marking-chennai" });
const STEPS = [{ title: "1. Requirement Assessment", desc: "Review your project scope, site conditions, and required deliverable format before mobilisation." }, { title: "2. Equipment Mobilisation", desc: "Verified survey team mobilised to site with appropriate instruments — total station, DGPS, or UAV." }, { title: "3. Field Data Collection", desc: "Field measurements are taken systematically following the survey scope agreed with the client." }, { title: "4. Data Processing & CAD", desc: "Field data is processed using CAD/GIS software to produce the required drawings and calculations." }, { title: "5. Report & Handover", desc: "Formal survey report issued with CAD drawings, data files, and recommendations as applicable." }];
const DELIVERABLES = ["Formal Survey Report", "CAD Drawing (DWG / PDF)", "Site Coordinate Data", "Area Calculations", "Measurement Certificate"];
const FAQS = [{ question: "How do I request this service?", answer: "Contact Buildogram with your plot details, survey type required, and location. We will connect you with a verified surveyor and provide a project-specific quote." }, { question: "How long does the survey take?", answer: "Typical field work takes 1–2 days. Report preparation and CAD output delivery takes 2–3 working days after field completion." }, { question: "Are the surveyors licensed?", answer: "Buildogram connects you with verified survey professionals. All surveyors in our network are assessed for equipment, experience, and past project quality." }, { question: "What format are the deliverables in?", answer: "Deliverables are provided as CAD DWG files, PDF drawings, and a formal written report. GIS or other formats can be requested at the time of enquiry." }];
export default function Page() { return (<main className="page" style={{ paddingTop: "80px", paddingBottom: "80px" }}><div className="sectionInner"><div style={{ marginBottom: "16px", fontSize: "14px", color: "#64748B" }}><a href="/" style={{ color: "#FC6E20" }}>Home</a> / <span style={{ color: "#0F172A", fontWeight: 600 }}>Construction Layout Marking in Chennai</span></div><h1 style={{ fontSize: "36px", fontWeight: 800, color: "#0F172A", marginBottom: "24px" }}>Construction Layout Marking in Chennai</h1><AnswerBlock question="What is construction layout marking and why is it critical?" answer="Construction layout marking transfers the approved structural drawing dimensions onto the actual ground — establishing exact column positions, pile points, and building setbacks. Errors at this stage propagate through the entire structure, making accurate layout marking essential before any excavation or piling begins." /><ProcessSteps title="Our Process" steps={STEPS} /><div style={{ background: "#F8FAFC", borderRadius: "16px", padding: "32px", margin: "40px 0" }}><h2 style={{ fontSize: "22px", fontWeight: 800, color: "#0F172A", marginBottom: "16px" }}>What You Receive</h2><ul style={{ listStyle: "none", padding: 0, display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: "12px" }}>{DELIVERABLES.map(d => (<li key={d} style={{ display: "flex", alignItems: "center", gap: "8px", fontSize: "15px", color: "#374151" }}><span style={{ color: "#10B981", fontWeight: 700 }}>✓</span> {d}</li>))}</ul></div><EntitySummary serviceName="Construction Layout Marking in Chennai" /><LocalIntentBlock /><FAQBlock title="Frequently Asked Questions" faqs={FAQS} /><div style={{ marginTop: "40px", padding: "24px", background: "#FFF7ED", borderRadius: "12px", border: "1px solid #FED7AA" }}><p style={{ fontWeight: 700, color: "#FC6E20", marginBottom: "12px" }}>Related Services</p><div style={{ display: "flex", flexWrap: "wrap", gap: "10px" }}>{[["Pile Point Marking", "/pile-point-marking-chennai"], ["Land Survey", "/land-survey-chennai"], ["Pile Foundation", "/pile-foundation-contractors-chennai"]].map(([label, href]) => (<Link key={href} href={href} style={{ padding: "8px 16px", background: "white", border: "1px solid #FED7AA", borderRadius: "100px", color: "#374151", fontSize: "14px", fontWeight: 600, textDecoration: "none" }}>{label}</Link>))}</div></div><div style={{ marginTop: "32px", textAlign: "center" }}><Link href="/contact?type=survey" className="btn btn-primary btn-lg">Request This Service</Link></div></div></main>); }
