import { generateSEOMetadata } from '@/lib/seo/metadata';
import Link from 'next/link';
import BreadcrumbSchema from '@/components/seo/BreadcrumbSchema';

export const metadata = generateSEOMetadata({
  title: 'Terms of Service | Buildogram',
  description: 'Read Buildogram\'s Terms of Service. Understand your rights and obligations when using our engineering-led construction platform in Chennai.',
  path: '/terms',
});

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: 'By accessing, registering on, or using the Buildogram platform — whether through our website, mobile application, or any associated service — you agree to be bound by these Terms of Service and all policies referenced herein, including our Privacy Policy and Disclaimer. If you do not agree to these terms, please discontinue use of our platform immediately. These terms constitute a legally binding agreement between you and Buildogram.',
  },
  {
    id: 'platform-role',
    title: '2. Platform Role — Advisory & Coordination',
    content: `Buildogram operates as an engineering-led advisory and coordination platform. Our role includes:

• Providing BOQ (Bill of Quantities) reviews, cost estimates, and structural analysis.
• Facilitating connections between property owners and verified independent partners (builders, contractors, architects, suppliers).
• Offering material sourcing support, site supervision coordination, and digital project documentation.
• Operating AI-assisted tools for preliminary estimates, plan analysis, and audit intake.

We are NOT a direct construction company. We do not employ construction workers, own construction equipment, or execute construction on your behalf. The final construction contract, workmanship responsibility, and site safety obligations rest entirely with the licensed contractor or partner you engage.`,
  },
  {
    id: 'user-responsibilities',
    title: '3. User Responsibilities',
    content: `As a user of Buildogram, you agree to:

• Provide accurate, complete, and current information when submitting project details, drawings, or enquiries.
• Not misrepresent the nature or scope of your project to obtain inaccurate estimates or reports.
• Use platform outputs (BOQ reviews, AI reports, cost estimates) as advisory inputs — not as final engineering certifications.
• Not copy, distribute, or commercially exploit any content, tools, or reports generated by our platform without written permission.
• Promptly verify all recommendations with a licensed engineer before commencing or modifying any construction activity.
• Keep your account credentials confidential and notify us immediately of any unauthorised access.`,
  },
  {
    id: 'material-pricing',
    title: '4. Material Pricing & Estimates',
    content: 'All material prices, construction cost estimates, and BOQ figures provided through our platform are estimates based on prevailing market rates at the time of generation. These figures are subject to change based on supplier availability, market conditions, logistics, taxation changes, and delivery timing. Buildogram does not guarantee that any quoted price will be the final transactional price. Users should obtain fresh written quotations from suppliers before committing to procurement.',
  },
  {
    id: 'partner-agreements',
    title: '5. Partner Agreements',
    content: 'When you engage a partner (builder, contractor, architect, supplier) discovered through Buildogram, the legal and commercial agreement is solely between you and that partner. Buildogram is not a party to such agreements. While we vet partners for basic credentials and past performance, we do not warrant or guarantee the quality of their work, their financial stability, or their adherence to project timelines. You are strongly advised to obtain a signed written contract from any partner before making any advance payments.',
  },
  {
    id: 'payment-terms',
    title: '6. Payment Terms',
    content: 'Fees for premium Buildogram services (BOQ reviews, structural audit facilitation, site supervision, Property Passport) are charged as disclosed at the time of service purchase. All payments are processed through secure payment gateways (Razorpay). Refund eligibility depends on the stage of service delivery — please refer to our Refund Policy or contact us for details. Payments made directly to partners or suppliers for construction materials and labour are independent of Buildogram and are not refundable through our platform.',
  },
  {
    id: 'intellectual-property',
    title: '7. Intellectual Property',
    content: 'All software, content, tools, templates, branding, and materials on the Buildogram platform are the exclusive intellectual property of Buildogram or its licensors, protected under applicable Indian copyright and trademark laws. You are granted a limited, non-exclusive, non-transferable licence to use the platform for your personal construction planning purposes. You may not reproduce, reverse engineer, scrape, or commercially exploit any part of the platform without prior written consent.',
  },
  {
    id: 'prohibited-use',
    title: '8. Prohibited Use',
    content: `You may NOT use the Buildogram platform to:

• Submit false project details to manipulate cost estimates or partner recommendations.
• Impersonate engineers, contractors, or Buildogram staff.
• Attempt to hack, scrape, or disrupt the platform or its infrastructure.
• Post or transmit offensive, defamatory, or illegal content.
• Use our platform for any purpose that violates applicable Indian laws and regulations.
• Circumvent our partner discovery system by using Buildogram introductions to engage partners while bypassing our coordination fees.

Violation of these terms may result in immediate account suspension, reporting to appropriate authorities, and legal action.`,
  },
  {
    id: 'termination',
    title: '9. Termination',
    content: 'Buildogram reserves the right to suspend or terminate your account at any time, with or without notice, if we have reason to believe you have violated these Terms of Service, engaged in fraudulent activity, or posed a risk to other users or the platform. You may terminate your account at any time by contacting us at support@buildogram.com. Upon termination, your right to use the platform ceases immediately. We will handle your data as described in our Privacy Policy.',
  },
  {
    id: 'limitation-of-liability',
    title: '10. Limitation of Liability',
    content: 'To the fullest extent permitted under applicable law, Buildogram\'s total liability for any claim arising out of or related to these Terms shall not exceed the fees paid by you to Buildogram in the 3 months prior to the claim. We shall not be liable for indirect, consequential, incidental, punitive, or special damages — including construction defects caused by partners, financial losses from material price changes, or project delays — even if we were advised of the possibility of such losses.',
  },
  {
    id: 'governing-law',
    title: '11. Governing Law & Dispute Resolution',
    content: 'These Terms of Service are governed by and construed in accordance with the laws of the State of Tamil Nadu, India, without regard to its conflict of law provisions. Any disputes arising from or relating to these Terms shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be subject to the exclusive jurisdiction of the courts in Chennai, Tamil Nadu, India.',
  },
];

export default function Terms() {
  return (
    <>
      {/* Hero */}
      <section style={{ background: 'var(--secondary)', padding: '60px 0', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse at 30% 50%, rgba(252,110,32,0.06) 0%, transparent 60%)' }} />
        <div className="container" style={{ position: 'relative' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(252,110,32,0.12)', border: '1px solid rgba(252,110,32,0.25)', borderRadius: '999px', padding: '5px 14px', marginBottom: '16px' }}>
            <span style={{ color: 'var(--primary)', fontSize: '12px', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase' }}>Legal</span>
          </div>
          <h1 style={{ color: 'white', fontSize: 'clamp(26px, 4vw, 40px)', fontWeight: 800, marginBottom: '10px', lineHeight: 1.2 }}>Terms of Service</h1>
          <p style={{ color: 'rgba(255,255,255,0.55)', fontSize: '14px' }}>Last updated: July 2026</p>
        </div>
      </section>

      {/* Table of Contents */}
      <div style={{ background: 'var(--bg-card2)', borderBottom: '1px solid var(--border)' }}>
        <div className="container" style={{ maxWidth: '860px', padding: '20px 24px' }}>
          <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '10px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Contents</p>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
            {sections.map((s) => (
              <a key={s.id} href={`#${s.id}`} style={{ fontSize: '13px', color: 'var(--primary)', background: 'rgba(252,110,32,0.08)', borderRadius: '999px', padding: '4px 12px', textDecoration: 'none', border: '1px solid rgba(252,110,32,0.15)', whiteSpace: 'nowrap' }}>
                {s.title.split('.')[0].trim()}
              </a>
            ))}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="container" style={{ maxWidth: '860px', padding: '56px 24px 80px' }}>
        <p style={{ color: 'var(--text-muted)', fontSize: '15px', lineHeight: 1.8, marginBottom: '48px', padding: '20px 24px', background: 'var(--bg-card2)', borderRadius: 'var(--radius)', borderLeft: '4px solid var(--primary)' }}>
          These Terms of Service govern your use of the Buildogram platform. Please read them carefully. By using our services, you agree to be bound by these terms. For questions, contact us at{' '}
          <a href="mailto:support@buildogram.com" style={{ color: 'var(--primary)' }}>support@buildogram.com</a>.
        </p>

        {sections.map((section) => (
          <section key={section.id} id={section.id} style={{ marginBottom: '44px', scrollMarginTop: '90px' }}>
            <h2 style={{ fontSize: '19px', fontWeight: 700, color: 'var(--secondary)', borderLeft: '4px solid var(--primary)', paddingLeft: '16px', marginBottom: '14px', lineHeight: 1.3 }}>
              {section.title}
            </h2>
            <div style={{ color: 'var(--text)', lineHeight: 1.85, fontSize: '15px', whiteSpace: 'pre-line' }}>{section.content}</div>
          </section>
        ))}

        {/* Contact CTA */}
        <div style={{ marginTop: '56px', padding: '32px', background: 'var(--bg-card2)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border)', textAlign: 'center' }}>
          <h3 style={{ fontSize: '18px', color: 'var(--secondary)', marginBottom: '8px' }}>Questions about our Terms?</h3>
          <p style={{ color: 'var(--text-muted)', fontSize: '14px', marginBottom: '20px' }}>Our team is happy to explain any aspect of how Buildogram works and what these terms mean for you.</p>
          <Link href="/contact" className="btn btn-primary">Contact Us</Link>
        </div>
      </div>

      <BreadcrumbSchema items={[{ name: 'Home', path: '/' }, { name: 'Terms of Service', path: '/terms' }]} />
    </>
  );
}
