import BreadcrumbSchema from '@/components/seo/BreadcrumbSchema';
﻿import { generateSEOMetadata } from '@/lib/seo/metadata';
import AnswerBlock from '@/components/seo/AnswerBlock';
import EntitySummary from '@/components/seo/EntitySummary';
import ProcessSteps from '@/components/seo/ProcessSteps';
import FAQBlock from '@/components/seo/FAQBlock';
import LocalIntentBlock from '@/components/seo/LocalIntentBlock';
import Link from 'next/link';
export const metadata = generateSEOMetadata({ title: 'Residential Structural Audit Chennai | House & Villa Safety Check | Buildogram', description: 'Buildogram provides engineer-led Residential Structural Audit in Chennai services in Chennai. Evidence-backed, report-based assessment by verified engineers.', path: '/residential-structural-audit-chennai' });
const STEPS = [{ title: '1. Site Visit & Scope', desc: 'Engineer visits the site to assess conditions, define test locations, and confirm the scope of work.' }, { title: '2. Testing & Data Collection', desc: 'Testing is performed using calibrated equipment following IS/ASTM standards. All readings are documented.' }, { title: '3. Data Analysis', desc: 'Collected data is analysed and compared against design specifications and code requirements.' }, { title: '4. Report Preparation', desc: 'A formal technical report is prepared with findings, observations, and engineer recommendations.' }, { title: '5. Report Delivery', desc: 'Report is delivered digitally with all data logs, photographs, and conclusion summary.' }];
const DELIVERABLES = ['Formal Technical Report', 'Test Data Logs', 'Photographic Evidence', 'Defect Location Map', 'Engineer Recommendations'];
const FAQS = [{ question: 'How do I book this service?', answer: 'Contact Buildogram with your building address, type of structure, and area of concern. We will assign a qualified engineer and confirm the schedule.' }, { question: 'How long does the testing take?', answer: 'Field testing for a typical residential building takes half a day to one full day. Report preparation takes 3–5 working days.' }, { question: 'Is this test destructive?', answer: 'Most NDT tests are non-destructive — they do not damage the structure. Core testing requires small-diameter drilling but is localised and repaired after sampling.' }, { question: 'What standards are used?', answer: 'All tests follow relevant IS (Indian Standard) codes and ASTM standards as applicable to the specific test method.' }];
export default function Page() { return ( <><main className='page' style={{ paddingTop: '80px', paddingBottom: '80px' }}><div className='sectionInner'><div style={{ marginBottom: '16px', fontSize: '14px', color: '#64748B' }}><a href='/' style={{ color: '#FC6E20' }}>Home</a> / <span style={{ color: '#0F172A', fontWeight: 600 }}>Residential Structural Audit in Chennai</span></div><h1 style={{ fontSize: '36px', fontWeight: 800, color: '#0F172A', marginBottom: '24px' }}>Residential Structural Audit in Chennai</h1><AnswerBlock question='Why should homeowners get a residential structural audit?' answer='A residential structural audit identifies hidden structural risks in houses, villas, and apartments — including foundation settlement, corrosion of reinforcement, crack severity, and material degradation — before they escalate into costly failures or safety hazards.' /><ProcessSteps title='Our Process' steps={STEPS} /><div style={{ background: '#F8FAFC', borderRadius: '16px', padding: '32px', margin: '40px 0' }}><h2 style={{ fontSize: '22px', fontWeight: 800, color: '#0F172A', marginBottom: '16px' }}>What You Receive</h2><ul style={{ listStyle: 'none', padding: 0, display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '12px' }}>{DELIVERABLES.map(d => (<li key={d} style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '15px', color: '#374151' }}><span style={{ color: '#10B981', fontWeight: 700 }}>✓</span> {d}</li>))}</ul></div><EntitySummary serviceName='Residential Structural Audit in Chennai' /><LocalIntentBlock /><FAQBlock title='Frequently Asked Questions' faqs={FAQS} /><div style={{ marginTop: '40px', padding: '24px', background: '#FFF7ED', borderRadius: '12px', border: '1px solid #FED7AA' }}><p style={{ fontWeight: 700, color: '#FC6E20', marginBottom: '12px' }}>Related Services</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>{[['Structural Audit','/structural-audit-chennai'],['NDT Testing','/ndt-testing-chennai'],['Crack Inspection','/building-crack-inspection-chennai'],['Old Building Audit','/old-building-structural-audit-chennai']].map(([label, href]) => (<Link key={href} href={href} style={{ padding: '8px 16px', background: 'white', border: '1px solid #FED7AA', borderRadius: '100px', color: '#374151', fontSize: '14px', fontWeight: 600, textDecoration: 'none' }}>{label}</Link>))}</div></div><div style={{ marginTop: '32px', textAlign: 'center' }}><Link href='/contact?type=audit' className='btn btn-primary btn-lg'>Request This Service</Link></div></div></main>  <BreadcrumbSchema items={[{"name":"Home","path":"/"},{"name":"Residential Structural Audit Chennai","path":"/residential-structural-audit-chennai"}]} />
    </>
  ); }
