'use client';
import { useState, useEffect } from 'react';
export default function AIToolsAdmin() {
  const [subs,setSubs]=useState([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState('all');
  useEffect(()=>{fetch('/api/ops/ai-tool-submissions').then(r=>r.json()).then(d=>{setSubs(d.data||[]);setLoading(false);}).catch(()=>setLoading(false));},[]);
  const filtered=filter==='all'?subs:subs.filter(s=>s.tool_name===filter);
  const tools=[...new Set(subs.map(s=>s.tool_name).filter(Boolean))];
  return (<div style={{padding:'32px',fontFamily:'Inter,sans-serif'}}><div style={{marginBottom:'24px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1 style={{fontSize:'22px',fontWeight:800,color:'#0F172A',margin:0}}>AI Tool Submissions</h1><p style={{color:'#64748B',fontSize:'14px',margin:'4px 0 0'}}>Submissions from AI-engineered construction tools</p></div><select value={filter} onChange={e=>setFilter(e.target.value)} style={{padding:'8px 12px',border:'1px solid #E2E8F0',borderRadius:'8px',fontSize:'14px',color:'#374151'}}><option value="all">All Tools</option>{tools.map(t=>(<option key={t} value={t}>{t}</option>))}</select></div>{loading?(<div style={{textAlign:'center',color:'#64748B',padding:'60px'}}>Loading...</div>):filtered.length===0?(<div style={{textAlign:'center',color:'#64748B',padding:'60px',background:'#F8FAFC',borderRadius:'12px'}}>No AI tool submissions yet.</div>):(<div style={{background:'white',border:'1px solid #E2E8F0',borderRadius:'12px',overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr style={{background:'#F8FAFC',borderBottom:'1px solid #E2E8F0'}}>{['Tool Name','Name','Phone','Email','Status','Date'].map(h=>(<th key={h} style={{padding:'12px 16px',textAlign:'left',fontSize:'12px',fontWeight:700,color:'#64748B',textTransform:'uppercase',letterSpacing:'0.5px'}}>{h}</th>))}</tr></thead><tbody>{filtered.map((s,i)=>(<tr key={s.id} style={{borderBottom:'1px solid #F1F5F9',background:i%2===0?'white':'#FAFAFA'}}><td style={{padding:'12px 16px',fontWeight:600,color:'#FC6E20',fontSize:'14px'}}>{s.tool_name}</td><td style={{padding:'12px 16px',color:'#0F172A',fontSize:'14px'}}>{s.name||'—'}</td><td style={{padding:'12px 16px',color:'#374151',fontSize:'14px'}}>{s.phone||'—'}</td><td style={{padding:'12px 16px',color:'#374151',fontSize:'14px'}}>{s.email||'—'}</td><td style={{padding:'12px 16px'}}><span style={{background:s.status==='reviewed'?'#DCFCE7':'#EFF6FF',color:s.status==='reviewed'?'#16A34A':'#3B82F6',fontSize:'11px',fontWeight:700,padding:'4px 10px',borderRadius:'100px'}}>{s.status||'submitted'}</span></td><td style={{padding:'12px 16px',color:'#64748B',fontSize:'13px'}}>{s.created_at?new Date(s.created_at).toLocaleDateString('en-IN'):'—'}</td></tr>))}</tbody></table></div>)}</div>);
}
