'use client';
/**
 * Icon.jsx
 * Maps icon name strings to Lucide React icons.
 * Used to replace broken emoji characters across the site.
 *
 * Usage:
 *   <Icon name="building" size={24} color="var(--primary)" />
 *
 * Add new icon mappings below as needed.
 */

import {
  Building2,
  Building,
  ClipboardList,
  ShoppingCart,
  Eye,
  FileCheck,
  FileText,
  Search,
  Wrench,
  HardHat,
  Hammer,
  Layers,
  MapPin,
  Ruler,
  Shield,
  Star,
  CheckCircle,
  AlertTriangle,
  ArrowRight,
  Home,
  Users,
  Phone,
  Mail,
  Calendar,
  Clock,
  DollarSign,
  TrendingUp,
  Award,
  Zap,
  Package,
  Truck,
  Microscope,
  Activity,
  BarChart2,
  Mountain,
  Shovel,
  Settings,
  Lock,
  Globe,
  Sun,
  Droplets,
  ThumbsUp,
  BookOpen,
  HelpCircle,
  Info,
  ChevronRight,
  Drill,
  Compass,
  FlaskConical,
  Cpu,
  Lightbulb,
  TreePine,
  Factory,
  Warehouse,
  PenTool,
  Camera,
  Video,
  Map,
  Navigation,
  Radio,
  Waves,
  Wind,
  Beaker,
  Box,
  Boxes,
  BrickWall,
  CircleCheck,
  Construction,
  Forklift,
  Gauge,
  Gavel,
  HardDrive,
  Landmark,
  LayoutDashboard,
  LineChart,
  Network,
  Percent,
  PieChart,
  Pipette,
  Receipt,
  Scan,
  Scale,
  ScanLine,
  Thermometer,
  Timer,
  Tool,
  Triangle,
  Workflow,
} from 'lucide-react';

const ICON_MAP = {
  // Service icons
  building: Building2,
  building2: Building,
  clipboard: ClipboardList,
  cart: ShoppingCart,
  eye: Eye,
  'file-check': FileCheck,
  file: FileText,
  search: Search,
  wrench: Wrench,
  'hard-hat': HardHat,
  hammer: Hammer,
  layers: Layers,
  pin: MapPin,
  ruler: Ruler,
  shield: Shield,
  star: Star,
  check: CheckCircle,
  alert: AlertTriangle,
  arrow: ArrowRight,
  home: Home,
  users: Users,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  clock: Clock,
  dollar: DollarSign,
  trending: TrendingUp,
  award: Award,
  zap: Zap,
  package: Package,
  truck: Truck,
  microscope: Microscope,
  activity: Activity,
  chart: BarChart2,
  mountain: Mountain,
  shovel: Shovel,
  settings: Settings,
  lock: Lock,
  globe: Globe,
  sun: Sun,
  water: Droplets,
  thumbsup: ThumbsUp,
  book: BookOpen,
  help: HelpCircle,
  info: Info,
  chevron: ChevronRight,
  drill: Drill,
  compass: Compass,
  flask: FlaskConical,
  cpu: Cpu,
  lightbulb: Lightbulb,
  tree: TreePine,
  factory: Factory,
  warehouse: Warehouse,
  pen: PenTool,
  camera: Camera,
  video: Video,
  map: Map,
  navigation: Navigation,
  radio: Radio,
  waves: Waves,
  wind: Wind,
  beaker: Beaker,
  box: Box,
  boxes: Boxes,
  brick: BrickWall,
  'circle-check': CircleCheck,
  construction: Construction,
  forklift: Forklift,
  gauge: Gauge,
  gavel: Gavel,
  'hard-drive': HardDrive,
  landmark: Landmark,
  dashboard: LayoutDashboard,
  'line-chart': LineChart,
  network: Network,
  percent: Percent,
  'pie-chart': PieChart,
  pipette: Pipette,
  receipt: Receipt,
  scan: Scan,
  scale: Scale,
  'scan-line': ScanLine,
  thermometer: Thermometer,
  timer: Timer,
  tool: Tool,
  triangle: Triangle,
  workflow: Workflow,
};

export default function Icon({ name = 'building', size = 24, color = 'currentColor', className = '', style = {} }) {
  const LucideIcon = ICON_MAP[name] || Building2;
  return (
    <LucideIcon
      size={size}
      color={color}
      className={className}
      style={style}
      aria-hidden="true"
    />
  );
}
